FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npx nest build users
RUN echo "=== Contenido de dist/ ===" && find dist/ -name "main.js" -type f
EXPOSE 8080
CMD ["node", "dist/apps/users/src/main.js"]
